/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Cyber.glb
Updated with custom materials + SelectiveBloom
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing";
import { BlendFunction } from "postprocessing";
import * as THREE from "three";

export function Room(props) {
  const { nodes, materials } = useGLTF(
    `${import.meta.env.BASE_URL}models/Cyber.glb`
  );

  // Refs for emissive meshes → fed into SelectiveBloom
  const glassRef = useRef();
  const lightBlueRef = useRef();
  const lightOrangeRef = useRef();

  // --- Custom material overrides ---

  // Main body: deep dark navy
  const bodyMaterial = new THREE.MeshStandardMaterial({
    color: "#08071f",
    roughness: 0.5,
    metalness: 0.15,
  });

  // Glass panels: purple emissive glow
  const glassMaterial = new THREE.MeshStandardMaterial({
    color: "#a020f0",
    emissive: "#bf00ff",
    emissiveIntensity: 1.2,
    roughness: 0.2,
    metalness: 0.0,
    transparent: true,
    opacity: 0.85,
  });

  // Blue light strips
  const lightBlueMaterial = new THREE.MeshStandardMaterial({
    color: "#003fcc",
    emissive: "#00aaff",
    emissiveIntensity: 1.8,
    roughness: 0.3,
  });

  // Orange light strips
  const lightOrangeMaterial = new THREE.MeshStandardMaterial({
    color: "#ff5500",
    emissive: "#ff7700",
    emissiveIntensity: 1.8,
    roughness: 0.3,
  });

  // Black detail parts
  const lightBlackMaterial = new THREE.MeshStandardMaterial({
    color: "#050505",
    roughness: 0.7,
    metalness: 0.1,
  });

  return (
    <group {...props} dispose={null}>
      <EffectComposer>
        <SelectiveBloom
          selection={[glassRef, lightBlueRef, lightOrangeRef]}
          intensity={1.8}
          luminanceThreshold={0.1}
          luminanceSmoothing={0.9}
          blendFunction={BlendFunction.ADD}
        />
      </EffectComposer>

      <group position={[1.128, 2.035, 1.83]} scale={[2.877, 0.194, 2.877]}>
        <mesh
          geometry={nodes.Cube001_1.geometry}
          material={bodyMaterial}
        />
        <mesh
          ref={glassRef}
          geometry={nodes.Cube001_2.geometry}
          material={glassMaterial}
        />
        <mesh
          ref={lightBlueRef}
          geometry={nodes.Cube001_3.geometry}
          material={lightBlueMaterial}
        />
        <mesh
          ref={lightOrangeRef}
          geometry={nodes.Cube001_4.geometry}
          material={lightOrangeMaterial}
        />
        <mesh
          geometry={nodes.Cube001_5.geometry}
          material={lightBlackMaterial}
        />
      </group>
    </group>
  );
}

useGLTF.preload(`${import.meta.env.BASE_URL}models/Cyber.glb`);